### PR TITLE
Patch - Fix error callback when zero byte file

### PR DESCRIPTION
**Pull request by terrancesnyder**
Fix issue when trying to load an invalid/zero byte font file

### CODE REVIEW

**Comment by fdb** [comment]
Thanks for the PR! It seems you have some style issue — could you update this so the tests pass? Then I'll gladly accept this!

**Comment by fpirsch** [comment]
Please note that I have included a `.editorconfig` file to help with these style issues. If you are using an [editorconfig](http://editorconfig.org/) compliant editor or IDE, those indentation, new line and trailing whitespace issues are automatically resolved.

**Comment by fdb** [comment]
@fpirsch much appreciated!

**Comment by Jolg42** [comment]
This code is already in master now, see https://github.com/nodebox/opentype.js/blob/a95e2ecd8901800cd84b60117c73f24b13925ca1/src/opentype.js#L360

I'm closing the PR.

**Pull request closed without merging**
