### PR TITLE
fonts/Roboto-Black.ttf updated, fixes #310

### LINKED ISSUE #310: Update Roboto used in demos
## Expected Behavior
The demos (eg https://opentype.js.org/font-inspector.html) use the latest and greatest version of Roboto

## Current Behavior
The demo's version is from 2011 :(

## Possible Solution
Update the file

### PR DESCRIPTION
**Pull request by davelab6**
:)

### CODE REVIEW

**Comment by fdb** [comment]
Hi @davelab6, thanks for the update. I see that some of our sanity checks fail as they rely on parsing of Roboto. Would you mind updating the checks as well?

```
 1) opentype.js dist can work with the uncompressed distribution:
      AssertionError: { en: 'Roboto Black' } deepEqual { en: 'Roboto Bk' }
      + expected - actual
       {
      -  "en": "Roboto Black"
      +  "en": "Roboto Bk"
       }
      
      at Context.<anonymous> (test/distSpec.js:7:16)
  2) opentype.js dist can work with the compressed dist files:
      AssertionError: { en: 'Roboto Black' } deepEqual { en: 'Roboto Bk' }
      + expected - actual
       {
      -  "en": "Roboto Black"
      +  "en": "Roboto Bk"
       }
      
      at Context.<anonymous> (test/distSpec.js:15:16)
  3) glyph.js lazy loading lazily loads xMin:
      AssertionError: -3 == 5
      + expected - actual
      --3
      +5
      
      at Context.<anonymous> (test/glyph.js:15:20)
  4) glyph.js lazy loading lazily loads xMax:
      AssertionError: 1399 == 1319
      + expected - actual
      -1399
      +1319
      
      at Context.<anonymous> (test/glyph.js:19:20)
  5) glyph.js bounding box calculates a box for a linear shape:
      AssertionError: -3 == 5
      + expected - actual
      --3
      +5
      
      at Context.<anonymous> (test/glyph.js:47:20)
  6) glyph.js bounding box calculates a box for a quadratic shape:
      AssertionError: 72 == 89
      + expected - actual
      -72
      +89
      
      at Context.<anonymous> (test/glyph.js:56:20)
  7) opentype.js can load a TrueType font:
      AssertionError: { en: 'Roboto Black' } deepEqual { en: 'Roboto Bk' }
      + expected - actual
       {
      -  "en": "Roboto Black"
      +  "en": "Roboto Bk"
       }
      
      at Context.<anonymous> (test/opentypeSpec.js:7:16)
```

**Comment by Jolg42** [comment]
Hi @davelab6 Did you have time to fix the tests?

Just run `npm run test` on your computer to see if all tests are green ;-)

**Comment by davelab6** [comment]
I'm sorry but I don't have the background required to do this quickly, it would be better for you to do it :)

**Comment by Jolg42** [comment]
@davelab6 👍

**Comment by Jolg42** [comment]
I committed a WIP of the merge on https://github.com/nodebox/opentype.js/commit/af447e6c31bf64f340184005f504ec1cbf54af90

But can't get rid of that error:
screenshot 2018-02-19 at 16 45 03

It looks like it's because the new font `post` table version is `3` but I don't have enough time to investigate more... 

@fpirsch Do you have an idea of what's happening?

**Comment by fpirsch** [comment]
@Jolg42 Yes, it is because of a version 3 post table.
As the doc says: "This version specifies that no PostScript name information is provided for the glyphs in this font file."
So this test should be reserved for a font with a post table version < 3.

**Comment by fpirsch** [comment]
Most of the embedded fonts have a v3 post table.
Vibur.woff has a v2.

**Comment by Jolg42** [comment]
Indeed @fpirsch!
So I can just remove that line and finish merging then... 😃

**Comment by Jolg42** [comment]
Merged in master with https://github.com/nodebox/opentype.js/commit/964a82b41f05ac275be785b689fceb856de28ac1

**Pull request closed without merging**
