### PR TITLE
Use ES6 modules.

### PR DESCRIPTION
**Pull request by fdb**
Convert the old require-style modules to native ES6 modules.

This is a (partial) fix for #260 and preparation for #247.

### CODE REVIEW

**Comment by fdb** [comment]
Thanks for checking it out! I'm testing a bit deeper for interop within node.js, once that works I'll merge.

**Comment by fdb** [comment]
Node.js doesn't support ES6 imports yet, so I've updated `package.json` to refer to the precompiled `dist/opentype.js` (same as the one we use in the browser).

This works, but apparently adding a ES2015-compatible `module` property in `package.json` is also a good idea ([read why here](https://github.com/rollup/rollup/wiki/pkg.module)). However, I don't have anything to test this with, so I'm keeping it as-is for now.

**Comment by Jolg42** [comment]
I see! I like the idea of adding an ES2015-compatible `module` to support older Node.js versions.

So if we do this we'll need to watch & build the dist file when debugging for Node.js for example? We should add a note and a simple `npm run` command for that I think.

**Comment by fdb** [comment]
I've added a `npm run watch` command to watch for changes. I've also switched to Rollup which made working with source maps easier, and also adds support for tree shaking, which should result in smaller builds.

**Comment by Jolg42** [comment]
Tree-shaking is cool :+1: 
Could you add https://github.com/mjeanroy/rollup-plugin-license or I could add it later, to keep the header in dist files?

**Comment by axkibe** [comment]
Nice, proper tree shaking will require API changes in a future step, however.

Since now, much behavior is decided by calling options. like load() can take any extension and thus has all font formats linked to it, the tree shaker has to include all. loadTTF() loadPS() or so would only be able to do those formats and thus only included that code trees. One could still provide an overall load() that selectes the other load functions.

Similar thing with fonthinting. It is activated by options.hinting = true, as command line option. So even somebody who never wants to do it, has the code in its build even when shaken. Here an option that actually requires importing an object would be better, since only then the trees would be linked.

**Comment by fdb** [comment]
@axkibe I agree -- we need some way to check for a font signature (e.g. `wOFF`), then dynamically require that code in a separate module.

**Comment by fdb** [comment]
@Jolg42 I've added the license header.

**Comment by axkibe** [comment]
I'd say rather you will have to have the user make it. And provide a catch-all loading function only for those that don't care if their bundle is going to include it all, even if not needed.

**Comment by fdb** [comment]
@axkibe If people want to use this in their own projects we can make it so that they only import the correct modules (e.g. no tiny-inflate if they just use desktop fonts). That will have to wait for another PR, though.

**Pull request merged**
