### PR TITLE
fontSize shouldn't be passed as string

### PR DESCRIPTION
**Pull request by axkibe**
In my opinion fontSize should not be passed as string encoded value to opentype.js

In the current implementation it doesn't matter, since as far I can see, it's only used in arithmetic operations where javascript will do an implicit conversation. However, it will be done each time and is considered relatively expensive.

It creates hugh issues in my upcoming fonthinting implementation, as there are fonthinting programms that compare to fontsize and branch depending on it and thus fail if integer !== string.

I leave it up to your decission if you want to typecheck in opentype.js and throw an error if typeof(fontSize) !== 'number' or it's just considered iligitimate usage where a user gets unexpected results if not using the API correctly. I'll do a check at least in the fonthinting part, as this can be a very subtle and nasty to find issue, as it isn't obvious, it just looks suboptimal, when the wrong font hinting branches get executed.

### CODE REVIEW

**Comment by Jolg42** [comment]
Hi @axkibe 
I agree that fontSize should not be a string, I think we can do some sort of parseInt() or parseFloat() (As I think that the CSS recommendation allows floats) and if the value is NaN throw an error with a specific message.
But this needs to be done for all methods in glyphs.js and font.js to be consistent.
Maybe somebody has a better idea?

**Comment by axkibe** [comment]
This is a design philosophical decission, personally I'm not a hugh fan of silently fixing things, but rather throwing an error, so the caller is made aware how to use the API correctly...

However, thats personal preference, some people like the "let me fix this for you" approch better..

**Comment by Jolg42** [comment]
Yes, less code is better code...! Maybe a simple parseFloat instead of parseInt would do the job + a small comment too to clarify that.

**Comment by axkibe** [comment]
Awww github appened the fonthinting pull request to this originally trivial one. I'll make a new one

**Pull request closed without merging**
