### PR TITLE
Added Google Closure externs file

### PR DESCRIPTION
**Pull request by Harbs**
I was not able to get an externs file to be generated automatically. The simplest solution turned out to be just creating the file manually.

It'll be some extra work updating the file as APIs change, but it should not be too bad.

I made some changes to the Substitution APIs to play better with ActionScript (which is the target I'm using). ActionScript requires optional parameters to be at the end of a signature. To accommodate this, I moved the "feature" and "sub" parameters to the beginning of the signatures.

### CODE REVIEW

**Comment by Jolg42** [comment]
@Harbs It looks like you're fighting with Travis!
Just do `$ npm run dist` in your terminal it will show you the errors in local 😉

**Comment by Harbs** [comment]
Thanks. I was about to ask how to get all these formatting checks to run locally. 😉

**Comment by Jolg42** [comment]
You can also squash everything to have only 1 commit in the end
http://eli.thegreenplace.net/2014/02/19/squashing-github-pull-requests-into-a-single-commit

**Comment by Harbs** [comment]
FWIW, NodeJS seems to freeze when I try running dist locally. It gets through all the 110 tests and then hangs. No idea why. Maybe I should update my version of NodeJS...

Git scares me. I'll leave all the commits unless you want me to squash them.

**Comment by fpirsch** [comment]
@Harbs NodeJS doesn't freeze, it's working heavily. The code style tests take quite some time.
If you don't want to squash your commits, just pass the tests locally first then commit just once at the end :-)

**Comment by Harbs** [comment]
I let it run for several minutes. It's hard to imagine that it would not have completed in that amount of time. I'll let it run longer and see.

I'll try to see about squashing the commits...

**Comment by Jolg42** [comment]
@Harbs That's weird :/ Maybe you have an old version of Node.js and updating it will resolve that…

For squashing the commits I think @fdb can do it from the repo…
https://help.github.com/articles/about-pull-request-merge-squashing/ 

This is a new feature to activate as an repo admin to allow squash & merge
screenshot 2016-08-02 at 13 08 34

**Comment by Harbs** [comment]
I let it run for about 15 minutes and it finally completed. There were a whole pile of errors due to a lot of bower files. I'm not sure what I did to cause them to be added. I assume the bower files was causing the long test time. I deleted them, and running dist finished in under 10 seconds.

I've been trying to figure out squashing, and I have not been very successful. If @fdb can do it instead, that would be very helpful.

**Comment by Harbs** [comment]
Both the JSDocs and the externs file should now be usable. It would be nice to setup the JSDocs to build automatically and deploy the docs somewhere, but I'm not sure how to set that up.

**Comment by fdb** [comment]
@Jolg42 Merge and squash commits are allowed 😄 

For deploying the docs, that looks like something I can do. I'm in the first stages of making new docs, which would also include the API docs.

**Comment by Harbs** [comment]
Cool. Looking forward! 😎 

I'm done with this for now unless you have something you want me to fix.

**Comment by Jolg42** [comment]
Merged in #211

**Comment by Harbs** [comment]
There were more doc improvements and an added extern file which was added after PR 211 that were not merged.

**Comment by Jolg42** [comment]
@Harbs Oops! 🙏 -> Merged 👍 :)

**Comment by Harbs** [comment]
Thanks! 👍

**Comment by Jolg42** [comment]
@fpirsch FYI @Harbs changed the order for the GSUB functions from "function(script, language, feature)" to "function(feature, script, language)" with 'DFLT' as default value for script & language.

See https://github.com/nodebox/opentype.js/pull/213/files#diff-73a1977ad0bdd68c4efca3b8cabfa413R79

**Comment by Harbs** [comment]
Correct.

I explained in the commit message the reason I did so. ActionScript does not allow mandatory parameters to come after optional ones. I will be targeting opentype.js from ActionScript (using FlexJS).

**Comment by fpirsch** [comment]
@Jolg42 @Harbs Fine with me. Makes sense.

**Pull request merged**
