### PR TITLE
Add support for the remaining CFF Type 2 CharString flex operators (flex, hflex and hflex1)

### PR DESCRIPTION
**Pull request by miguelsousa**
I've expanded on @tshinnic's groundwork and added support for the remaining flex operators. Relates to issue #85.

### CODE REVIEW

**Comment by miguelsousa** [comment]
Here are before and after screenshots using the font TrajanPro-Regular.otf
before
after

**Comment by fdb** [comment]
Awesome work, thanks! Can I list you under AUTHORS?

**Comment by miguelsousa** [comment]
Sure. Thank you!

**Comment by fdb** [comment]
No problem, thanks again!

**Comment by tshinnic** [comment]
Thanks for pointing out a font that demonstrated the failures when the operators were unhandled.  Finding a font that exercises a particular feature is rather a pain.

And I just love the very explicit 
```Javascript
            // y = y;       // dy6
```
Comments that mean the code reader doesn't have to think! Golden.  :smile:

**Comment by miguelsousa** [comment]
You're welcome. I work at Adobe in the Type Development team, so I'm quite familiar with the font formats that were invented here. Due to its design features, I knew that Trajan would be one of the font families quite affected by the lack of support for the flex operators.
I think that there are one or two more operators from the 12 series that should probably be supported, since they occur seldomly; the `div` comes to mind, which is used for representing non-integer coordinates. We have a substantial font repository in-house that I can test with. I'll open up an issue or submit a patch if I find anything.

Glad my first contribution went so well. Looking forward to do more of it. `opentype.js` is awesome, and I can easily see it becoming the foundation layer for any browser-based font tool.

**Pull request merged**
