### PR TITLE
Addressing issues #168 related to not supporting multi byte characters

### PR DESCRIPTION
**Pull request by talltyler**
JavaScript strings handle two byte characters as two items which breaks some multi lingual and emoji support.

## Motivation and Context
This addresses https://github.com/nodebox/opentype.js/issues/168

## How Has This Been Tested?
npm test passes. And this has been tested in IE 11 and Chrome.

## Types of changes
Mostly this just uses a for...of loop if the browser enables it. Because this is a new feature checks are made to make sure this method is available, and the build tools have been updated to support these changes.

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I did `npm run test` and all tests passed green (including code styling checks).
- [ ] I have added tests to cover my changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the **README** accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by schuylr** [comment]
I tried your branch with a non-BMR character (this one: 🙂 ) on a font I made with a flat vector path (no colour like #193 mentions), and I still get a blank square. I'm using `getPath` and `toPathData` on the response.

**Comment by talltyler** [comment]
This branch doesn't solve any of the rendering issues these types of glyphs. It only allows multibyte characters to be passed through the system and handled as single units rather than two unrelated code points.

**Comment by schuylr** [comment]
I understand that, but I made a custom font with the same sort of glyphs that you would find in the ASCII/BMR range and it still didn't work. The result was still a blank square.

**Comment by talltyler** [comment]
Can you post this font and the character that you are passing in?

**Comment by schuylr** [comment]
[Cursive.ttf.zip](https://github.com/nodebox/opentype.js/files/1459006/Cursive.ttf.zip)

The character I tried is above. "slightly smiling face" or `U+1F642`

**Comment by fpirsch** [comment]
Closed through #338

**Pull request closed without merging**
