### PR TITLE
Improve TABLE writing to support nested subtables

### PR DESCRIPTION
**Pull request by fpirsch**
Complex tables such as GPOS and GSUB heavily use nested subtables.
Supporting this feature will make it easier to create fonts with kerning and ligatures.

### CODE REVIEW

**Comment by fdb** [comment]
This looks awesome. Thanks!

**Comment by behdad** [comment]
Note that GSUB/GPOS don't use deeply-nested subtables per se, whereas they refer to other structs by offset.  It is part of the design of the table that the same object can be encoded once and referred to from multiple locations.

**Comment by fpirsch** [comment]
It appears there is a misunderstanding here.
You're right, "reference by offset" is what I meant by subtable. Like coverageTable, scriptTable, langSysTable and all "tables" defined in the spec.
But `type:TABLE` is sometimes used here merely to group fields together, without deporting the data to the end and referencing by offset. This IMHO is not correct since this is not what the spec calls a table.
Thanks to the unit tests, I spotted and fixed this in `test/name.js` and `tables/fvar.js`.

However @Jolg42 just notified me that this PR introduces a regression as `cff.js` (at least) also uses `type:TABLE` incorrectly.
Seems we need more unit testing :-)

**Comment by FranzPoize** [comment]
I confirm that after the latest PR the font generated cannot be loaded inside a browser in Prototypo.

Here is the output of ot-sanitise :
```
ERROR:  6 F: invalid table tag
Failed to sanitise file!
```

I'll try to look into this or provide a unit test.

**Comment by FranzPoize** [comment]
I'm currently trying to fix and convert the cff table to a table of the right types.

**Comment by fpirsch** [comment]
Oh OK, I was going to do it.

**Comment by FranzPoize** [comment]
@fpirsch there seems to be some regression on the construction of the cff table record also which makes extensive use of the ``TABLE`` type.

The table type doesn't seem to have been design to handle subtabling nicely and I find myself not really up to refactoring all the tables that are used as arrays. I think one simple way is to add a ``SUBTABLE`` type that can be used for offseted subtables and to keep the current ``TABLE`` type as is.

This is what I came up with https://github.com/FranzPoize/opentype.js/commit/011f3039817187e76b88403f547b5d6b6618eb47

**Comment by fpirsch** [comment]
I'll try tro find some time to finish this tonight. Technically it could look like what you've done @FranzPoize, but I'd like to keep TABLE for what the spec describes as tables.

**Comment by fpirsch** [comment]
This should be fixed by #177 (`node generate-font-node` is working again).

@behdad The "once instance - multiple references" feature is not implemented here. Hopefully it will come later.

**Comment by mattlag** [comment]
Hi @fpirsch - Does this, by chance, enable kerning?  Writing GSUB/GPOS tables? There are a couple open issues around this #95 and #112 

Sorry for if this issue isn't quite what I think it is.  But, if it does happen to enable kerning, it would be great to have an abstracted method that does just kerning, or at the very least a table writing example.

Thanks!

**Comment by fpirsch** [comment]
@mattlag This does not enable writing GPOS/GSUB tables yet, but it's a step in this direction. And yes, GPOS/GSUP export is the goal here. I just need some time to work on it.

**Comment by mattlag** [comment]
@fpirsch Okay, thanks so much!  I didn't fully understand this work item, so I just wanted to double check :-)

**Pull request merged**
