### PR TITLE
GSUB and GPOS update

### PR DESCRIPTION
**Pull request by taylorb-monotype**
Add some support for OpenType font variations in GSUB. Allow version 1.1 in GSUB and GPOS. This was blocking use with some variable fonts.

### CODE REVIEW

**Comment by Jolg42** [comment]
Hi @taylorb-monotype Thanks for the PR!

Could you fix the issue found by Travis?
screenshot 2017-11-19 at 22 41 16
I'll merge it after that.

Also do you have a variable font to provide for testing?

**Comment by taylorb-monotype** [comment]
I believe I have fixed this issue below. Also, I have added two test fonts as described in the commit. These fonts may be used to test GSUB and GPOS table version 1.1.

Bob


 
Bob Taylor
Director, Software Engineering
600 Unicorn Park Drive 3rd Floor
Woburn, Massachusetts 01801
United States
Telephone +1 (781) 970 6086
monotype.com

**Comment by fdb** [comment]
Thanks for the PR!

It seems Travis is still complaining about a triple-equals instead of a double-equals:

screen shot 2017-11-24 at 08 35 32

Could you fix that? We can test it out some more and merge it.

**Comment by taylorb-monotype** [comment]
Should be fixed now. I also cleaned up some style issues detected by test. Sorry about that.

Bob


 
Bob Taylor
Director, Software Engineering
600 Unicorn Park Drive 3rd Floor
Woburn, Massachusetts 01801
United States
Telephone +1 (781) 970 6086
monotype.com

**Comment by taylorb-monotype** [comment]
What is the status of this pull request? Is there anything you need from me?

**Comment by Jolg42** [comment]
Hi @taylorb-monotype ;-)

I just cleaned the code style errors & merged it!

Just a tip for your next PR to make it easier for everybody:
- Run `npm run test` locally it will show you in order the unit test errors and code style errors after.
- Don't include files from the `dist` to avoid conflicts

Voilà!

**Pull request merged**
