### PR TITLE
Convert the path to a SVG <path> element as a html element

### PR DESCRIPTION
**Pull request by afternoon2**
I added a function, that returns an svg path as an html element, so you can add your newly rendered path straight into specific DOM element, without struggling with string parsing.

[Codepen Demo here.](http://codepen.io/jakub_antolak/pen/zNYMeK)

### CODE REVIEW

**Comment by fpirsch** [comment]
Hi @afternoon2,
this is a good idea.
The automated tests fail because of the indentation (please run `npm test` before committing).
The name `toHTML` suggests the function returns HTML code. Since it returns an SVG element, maybe it should have another more explicit name ?
Note also that `opentype.js` is intended to work also in non-browser environments (e.g. Node.js).

**Comment by fdb** [comment]
I agree regarding the naming. Perhaps `Path.toElement` or `Path.toDOMElement` are more appropriate names.

**Comment by afternoon2** [comment]
Yes, the name might be misleading. `Path.toDOMElement` is much better. My intention was to make a method that would be helpful while coding svg animations (live rendering svg from font), so it's not useful outside the browser.

I have some problems with `npm test.` I mean -after I corrected indentation, in git-bash I'm still seeing some linebreak issues (49):

`validateLineBreaks: Invalid line break at <filepath>`

And here's a dummy question: how to fix it without opening each broken file?

**Comment by fpirsch** [comment]
Yes, this is a pain if you are not using Linux.
To avoid this, I locally add the following line to the `.jscs` file before running `npm test`:
```
"validateLineBreaks": "CRLF",
```
Then I get only 1 error for `./bin/server.js`
Line break errors don't matter since they will be automatically and silently corrected when you commit on github (don't commit `.jscs`). You just have to make sure you don't have other types of errors.

Maybe jscs offers the possibility to disable linebreak checks but I don't know how.

**Comment by afternoon2** [comment]
That works, thank you!

**Comment by fdb** [comment]
Thanks!

**Pull request merged**
