### PR TITLE
Updated the extern file to reflect API changes

### PR DESCRIPTION
**Pull request by Harbs**

### CODE REVIEW

**Comment by Harbs** [comment]
I'm not sure how to squash my commits. The only changes should be in the last one.

**Comment by fpirsch** [comment]
`git rebase -i HEAD~6` :-)

**Comment by Harbs** [comment]
Thanks, but advanced git commands make me queasy.  ;) I think it can be squashed automatically when pulled in. If that's a problem I'll try the rebase...

**Comment by fdb** [comment]
Squashed and merged 😄

**Pull request merged**
