### PR TITLE
Support non-Basic-Multilingual-Plane (BMP) characters

### PR DESCRIPTION
**Pull request by antonytse**
## Description
A new pull request after changing the code per the comments in #331.

Replaced `charCodeAt()` to `codePointAt()`  in `encoding.js` and modified `font.js` to handle surrogate pairs, for supporting non-Basic-Multilingual-Plane characters (i.e. `U+10000` to `U+10FFFF`).

## Motivation and Context

It addresses #168 and #327, and the issue mentioned by @schuylr in #297.

## How Has This Been Tested?

1. `npm run test`
2. `npm run dist` and `npm run start` to check the usages of `opentype.js` via `http://localhost:8080`
3. Run the rendering test from https://github.com/unicode-org/text-rendering-tests. After the fix, it passed `CFF-1` and `CFF-2` test cases. Results in `GVAR-4`, `GVAR-5` and `GVAR-6`
4. Tested in Internet Explorer 11 for the polyfill of `String.prototype.codePointAt`

 are still incorrect, but the icon is shown instead of 2 dots. See the screenshots below.

## Screenshots (if appropriate):
CFF-1 and CFF-2
GVAR-4, GVAR-5 and GVAR-6

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I did `npm run test` and all tests passed green (including code styling checks).
- [ ] I have added tests to cover my changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the **README** accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by fpirsch** [comment]
In `stringToGlyphs`, there is a trick to iterate simply over characters without checking surrogate pairs :
```
const chars = [...s];
const indexes = [];
for (let i = 0; i < chars.length; i += 1) {
        const c = s[i];
        indexes.push(this.charToGlyphIndex(c));
}
```

**Comment by antonytse** [comment]
Thank you @fpirsch. I have tried to change the code as above but it seems to be broken after `rollup`, as `rollup-plugin-buble` converted the code as follow:
```
var this$1 = this;

var chars = [].concat( s );
var indexes = [];
for (var i = 0; i < chars.length; i += 1) {
    var c = chars[i];
    indexes.push(this$1.charToGlyphIndex(c));
}
```

`s` becomes the only element in the `chars` array and therefore `chars.length` always equal to `1`...

**Comment by fpirsch** [comment]
Thanks @antonytse for trying :-)
I should have thought about bublé. If new syntax doesn't transpile, we can use the new method with good old syntax `Array.from` and "ponyfill" it (just discovered the word).

```
// Array.from implementation for strings thanks to Mathias Bynens ( https://github.com/mathiasbynens/Array.from )
var arrayFromString = Array.from || (s => s.match(/[\uD800-\uDBFF][\uDC00-\uDFFF]?|[^\uD800-\uDFFF]|./g) || []);

arrayFromString('a💩b');       // ['a','💩','b']
```

**Comment by antonytse** [comment]
Thanks. I have added a commit for this. 😃

**Comment by fpirsch** [comment]
The `arrayFromString` will be created over and over again if it is declared inside the `stringToGlyphs`method. It should be placed in the top-level scope, after the imports.
Sorry @antonytse, it should be perfect after that :-)

**Pull request merged**
